# Generated by Django 3.0.6 on 2020-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200611_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='wordcloud_scores',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='wordcloud_words',
            field=models.TextField(default=''),
        ),
    ]
