"""
Django settings for derrick project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback: this file was previously committed with a real
# secret key in plaintext. Set DJANGO_SECRET_KEY in the environment; in
# DEBUG mode only, fall back to an obviously-fake local value.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or (
    'django-insecure-local-dev-only-do-not-use-in-production' if DEBUG else None
)
if not SECRET_KEY:
    raise RuntimeError(
        'DJANGO_SECRET_KEY environment variable must be set when DEBUG is off.'
    )

ALLOWED_HOSTS = ['localhost', '0.0.0.0', '34.234.193.247', 'api.thediversecandidate.com', 'thediversecandidate.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'background_task',
    'api',
    'rest_framework',
    'rest_framework.authtoken',

    'django_elasticsearch_dsl',

    'debug_toolbar',
    'silk',

    'corsheaders',
]

# SMMRY API PARAMS
SMMRY_API_ENDPOINT = "https://api.smmry.com"
SM_API_KEY = os.environ.get('SMMRY_API_KEY', '')
SM_LENGTH = 1 # No of sentences to summarize in
SM_KEYWORD_COUNT = 5
SM_URL = "" # url of webpage to summarize


ELASTICSEARCH_DSL = {
    'default': {
        'hosts' : 'localhost:9200'
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',

    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'derrick.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'derrick.wsgi.application'


import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname()) 
INTERNAL_IPS = [ip[:-1] + "1" for ip in ips]

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


CRONJOBS = [
    ('* * * * * . python', 'cron_jobs.scraper.run_scraping_job', '>> ' + os.path.join(BASE_DIR) + '/logs/scraper.log 2>&1')
]

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'


STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

CORS_ALLOWED_ORIGINS = [
    "http://thediversecandidate.com",
    "https://thediversecandidate.com",
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True
