# Generated by Django 3.0.6 on 2020-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='list_of_keywords',
            field=models.TextField(default=''),
        ),
    ]
